name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Set your branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t cleowoman/lrnd:latest -t cleowoman/lrnd:${{ github.sha }} .

    - name: Push the image
      run: |
        docker buildx create --use
        docker push cleowoman/lrnd:latest
        docker push cleowoman/lrnd:${{ github.sha }}
